---
- name: Coping the application file
  copy:
    src: helloworld.js
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: 0644
  notify: restart helloworld

- name: Copying the service file
  copy: 
    src: helloworld.conf
    dest: /etc/systemd/system/helloworld.service
    owner: root
    group: root
    mode: 0644

- name: Reload systemd
  command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'

- name: Enable and start HelloWorld service
  systemd:
    name: helloworld
    enabled: yes
    state: started
